version: "3.7"

services:
  bag-extract:
      build:
        context: .
        dockerfile: Dockerfile
      entrypoint: ["/bin/sh", "-c"]
      command: 
      - |
        prefect backend cloud
        prefect auth login --key $prefect_api_key
        python3 /opt/prefect/bag-extract/flow.py
      env_file:
      - .env
