version: "3.7"

services:
  enexis:
      build:
        context: .
        dockerfile: Dockerfile
      entrypoint: ["/bin/sh", "-c"]
      image: $image
      command: 
      - |
        prefect backend cloud
        prefect auth login --key $prefect_api_key
        python3 /opt/prefect/enexis/flow.py
      env_file:
      - .env
