name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY_HOSTNAME: gcr.io


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        flow: [bag-extract]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
       
      - name: Auth GCP
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{secrets.GCP_CONTAINER_REGISTRY_SA_KEY}}
       
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      
      - name: Auth Docker
        run: |
          gcloud auth configure-docker

      - name: Build Container
        uses: isbang/compose-action@v1.1.0
        with:
          compose-file: "./flows/${{matrix.flow}}/docker-compose.yml"
          up-flags: "--build"
